# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: 
   branches: 
      include: 
      - '*' 
   tags: 
      include: 
      - '*' 
pr: 
   branches: 
      include: 
      - '*'

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
         pip3 install --upgrade pip
         sudo apt-get update
         sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 libespeak1
         sudo apt-get install ffmpeg libav-tools
         sudo apt-get install python3-pyaudio
         pip3 install pyaudio
         pip3 install -r requirements.txt
  displayName:'installing dependencies'

- script: |
         chmod +x friday.py
         python3 ./friday.py
  displayName:'finishing'
